FROM golang:1.14-alpine as builder

WORKDIR /go/src/drone-email
COPY . .

ARG GOOS
ARG GOARCH
ARG GOARM=7
RUN CGO_ENABLED=0 go build


FROM alpine:3.11

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/src/drone-email/drone-email /bin/
ENTRYPOINT ["/bin/drone-email"]
